### ISSUE TITLE
Button not aligning left

### ISSUE THREAD

**Issue by mato0039** [mato0039/sections#1]
Hi Thomas, 

I am having an issue aligning the button left as well as aligning my text to the top of the image in the 960px and 1440px views. 

I've adjust my padding several times and nothing seems to work.

Please help! 

@thomasjbradley

<img width="485" alt="Screen Shot 2019-10-22 at 9 52 21 AM" src="https://user-images.githubusercontent.com/55108737/67293137-0367c880-f4b2-11e9-96c8-c6ca2c9ddef0.png">
<img width="946" alt="Screen Shot 2019-10-22 at 9 52 40 AM" src="https://user-images.githubusercontent.com/55108737/67293151-09f64000-f4b2-11e9-83dd-faf31598f69e.png">
<img width="684" alt="Screen Shot 2019-10-22 at 9 51 37 AM" src="https://user-images.githubusercontent.com/55108737/67293227-22665a80-f4b2-11e9-818f-d27e334c46ff.png">

**Comment by thomasjbradley** [comment]
Add `text-align: left` to `div` in CSS.
Remove the `margin-top` from `.image`—instead add `padding: 2em 0` to `section`

**Comment by mato0039** [comment]
Thank you!
